<?php

namespace App\Widgets;

use App\TaskManagement\DB\TaskRepo;

/**
 *  |--------------------------------------------------------------------------
 *  |   You can use the below snippets to override the defaults.
 *  |====== Remove this doc block if you don't need it ========
 *  |--------------------------------------------------------------------------
 *  | public $contextAs = '$data'; (default : '$data')
 *  | public $controller = '\App\ClassPath\ُSomeClass@someMethod'; (optional)
 *  | public $presenter = \App\ClassPath\WidgetPresenter::class; (optional)
 *  | public $minifyOutput = true; (use it to override the default value in config file)
 *  | public $cacheTags = []; (optional) (Available for all cache driver)
 *  | public $cacheLifeTime = 0;   (use it to override the default value in config file)
 *  | public $cacheView = false; You may only cache the controller result. (default : true)
 *  | public $template; (optional) (By default it looks for the view file generated by artisan)
 *  |--------------------------------------------------------------------------
 */
class DefaultTaskList
{
    public $template = 'Widgets::TaskListView';

	public function data()
	{
        $userId = auth()->id();

        return ['tasks' => TaskRepo::withDefaultState($userId)->get()];
    }

   /**
    * If the widget output depends on query strings you should return key names.
    * otherwise you get undesired results out of the cache store. for example:
    * example.com/product?page=1 and you use the page number in your db query
    * or if you want it to be separated for each user: return auth()->id();
    */
	public function cacheKey()
	{
        $userId = auth()->id();

        return 'task_list_'.$userId.'_not_started';
	}
}
